### ISSUE TITLE
2023 Roadmap 

### ISSUE THREAD

**Issue by adamchaboryk** [ryersondmp/sa11y#42]
## v2.3.6/v3.0 development branch
- [x] Refactoring. Store each issue as an object which is then pushed to a single results array. Clean up `checkAll` function.
- [x] Build light weight dismissal system to temporarily dismiss warnings. Inspired by Editoria11y.
- [x] Improve keyboard support for tooltips appended to document body.
- [x] SCSS refactoring to improve readability.
- ~Update TypeScript definition file.~

## Needs peer review/testing
- [x] RTL support.
- [x] Dismissible warnings.
- [x] `headless` prop: Use Sa11y in headless mode (no interface).
- [x] `selectorPath` prop: Generate CSS selector path of elements, which is then stored in an issue's object.

## Wish list/to-do (help wanted)
- [x] Create a prop to make all toggleable rulesets on by default (without ability to toggle off?)
- [x] Encapsulate annotations, toggle and panel into web components.
- [x] Support for querying web components/shadow DOM.
- [x] Support for Window's High Contrast Mode (WHCM).

## Adam's to-do list
- [x] Create accessibility statement on project website.
- [x] Make project website open source/public... add markdown support. ~Consider moving developer docs to GitHub wikis?~
- [ ] Explore current implementation of Sa11y in Joomla.

**Comment by brianteeman** [comment]
PS there was a good mention from Hidde de Vries on a11ytalks yesterday
YouTube - [Shifting Left: How CMS accessibility Can Help - Hidde de Vries (A11yTalks - April 2023)](https://youtu.be/ct-XbOeA79I?t=2179)

[slide deck](https://talks.hiddedevries.nl/gyxKUM/shifting-left-or-making-accessibility-easier-by-doing-it-earlier)

**Comment by adamchaboryk** [comment]
Awesome. Looking forward to it! Let me know if there's anything else I can do to make it easier for you to implement. 

And thanks for sharing the link. Great to see our work highlighted 😄

**Comment by adamchaboryk** [comment]
14/15 tasks complete ✅

@brianteeman, let me know how I can assist with the Joomla port of 3.0. I have Joomla installed locally and will be poking around over the next few weeks. Perhaps I can assist with the design of the back end settings page for Jooa11y. Keep me in the loop!

**Comment by brianteeman** [comment]
That would be awesome. I am finishing a project right now but will ping you in 2 weeks
